name: 'Mozilla Shell GitHub Action'
description: 'Run commands via the mozilla-build shell script'
author: 'EnderDev'
branding:
    icon: 'terminal'
    color: 'green'
runs:
  using: 'node12'
  main: 'dist/index.js'
